/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Wed Jan 31 10:43:05 2018. */

#include "actuated.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t _targetPowerStateParams_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, _targetPowerStateParams, targetPowerState, targetPowerState, 0),
    PB_LAST_FIELD
};

const pb_field_t _targetControlPolicyParams_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, _targetControlPolicyParams, targetControlPolicy, targetControlPolicy, 0),
    PB_LAST_FIELD
};

const pb_field_t _targetManualControlParams_fields[2] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, _targetManualControlParams, targetBrightnessLevel, targetBrightnessLevel, 0),
    PB_LAST_FIELD
};

const pb_field_t _targetAutoTimerParams_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, _targetAutoTimerParams, targetOnTime, targetOnTime, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, _targetAutoTimerParams, targetOffTime, targetOnTime, 0),
    PB_LAST_FIELD
};

const pb_field_t _targetAutoLuxParams_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, _targetAutoLuxParams, targetOnLux, targetOnLux, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, _targetAutoLuxParams, targetOffLux, targetOnLux, 0),
    PB_LAST_FIELD
};

const pb_field_t _targetConfigurations_fields[6] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, _targetConfigurations, targetPowerState, targetPowerState, &_targetPowerStateParams_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, _targetConfigurations, targetControlPolicyParams, targetPowerState, &_targetControlPolicyParams_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, _targetConfigurations, targetAutoTimerParams, targetControlPolicyParams, &_targetAutoTimerParams_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, _targetConfigurations, targetAutoLuxParams, targetAutoTimerParams, &_targetAutoLuxParams_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, _targetConfigurations, targetManualControlParams, targetAutoLuxParams, &_targetManualControlParams_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(_targetConfigurations, targetPowerState) < 65536 && pb_membersize(_targetConfigurations, targetControlPolicyParams) < 65536 && pb_membersize(_targetConfigurations, targetAutoTimerParams) < 65536 && pb_membersize(_targetConfigurations, targetAutoLuxParams) < 65536 && pb_membersize(_targetConfigurations, targetManualControlParams) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES__targetPowerStateParams__targetControlPolicyParams__targetManualControlParams__targetAutoTimerParams__targetAutoLuxParams__targetConfigurations)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(_targetConfigurations, targetPowerState) < 256 && pb_membersize(_targetConfigurations, targetControlPolicyParams) < 256 && pb_membersize(_targetConfigurations, targetAutoTimerParams) < 256 && pb_membersize(_targetConfigurations, targetAutoLuxParams) < 256 && pb_membersize(_targetConfigurations, targetManualControlParams) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES__targetPowerStateParams__targetControlPolicyParams__targetManualControlParams__targetAutoTimerParams__targetAutoLuxParams__targetConfigurations)
#endif


/* @@protoc_insertion_point(eof) */
