/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9-dev at Tue Aug 22 16:34:11 2017. */

#ifndef PB_ACTUATED_PB_H_INCLUDED
#define PB_ACTUATED_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Enum definitions */
typedef enum _ctrlPolicy {
    ctrlPolicy_AUTO_LUX = 0,
    ctrlPolicy_AUTO_TIMER = 1,
    ctrlPolicy_MANUAL = 2
} ctrlPolicy;
#define _ctrlPolicy_MIN ctrlPolicy_AUTO_LUX
#define _ctrlPolicy_MAX ctrlPolicy_MANUAL
#define _ctrlPolicy_ARRAYSIZE ((ctrlPolicy)(ctrlPolicy_MANUAL+1))

/* Struct definitions */
typedef struct _targetAutoLuxParams {
    bool has_targetOnLux;
    uint32_t targetOnLux;
    bool has_targetOffLux;
    uint32_t targetOffLux;
/* @@protoc_insertion_point(struct:targetAutoLuxParams) */
} targetAutoLuxParams;

typedef struct _targetAutoTimerParams {
    bool has_targetOnTime;
    uint32_t targetOnTime;
    bool has_targetOffTime;
    uint32_t targetOffTime;
/* @@protoc_insertion_point(struct:targetAutoTimerParams) */
} targetAutoTimerParams;

typedef struct _targetControlPolicy {
    ctrlPolicy controlPolicy;
/* @@protoc_insertion_point(struct:targetControlPolicy) */
} targetControlPolicy;

typedef struct _targetManualControlParams {
    bool has_targetBrightnessLevel;
    uint32_t targetBrightnessLevel;
/* @@protoc_insertion_point(struct:targetManualControlParams) */
} targetManualControlParams;

typedef struct _targetPowerStateParams {
    bool targetPowerState;
/* @@protoc_insertion_point(struct:targetPowerStateParams) */
} targetPowerStateParams;

typedef struct _targetConfigurations {
    bool has_PowerState;
    targetPowerStateParams PowerState;
    bool has_ControlPolicy;
    targetControlPolicy ControlPolicy;
    bool has_AutoTimerParams;
    targetAutoTimerParams AutoTimerParams;
    bool has_AutoLuxParams;
    targetAutoLuxParams AutoLuxParams;
    bool has_ManualControlParams;
    targetManualControlParams ManualControlParams;
/* @@protoc_insertion_point(struct:targetConfigurations) */
} targetConfigurations;

/* Default values for struct fields */

/* Initializer values for message structs */
#define targetPowerStateParams_init_default      {0}
#define targetControlPolicy_init_default         {(ctrlPolicy)0}
#define targetManualControlParams_init_default   {false, 0}
#define targetAutoTimerParams_init_default       {false, 0, false, 0}
#define targetAutoLuxParams_init_default         {false, 0, false, 0}
#define targetConfigurations_init_default        {false, targetPowerStateParams_init_default, false, targetControlPolicy_init_default, false, targetAutoTimerParams_init_default, false, targetAutoLuxParams_init_default, false, targetManualControlParams_init_default}
#define targetPowerStateParams_init_zero         {0}
#define targetControlPolicy_init_zero            {(ctrlPolicy)0}
#define targetManualControlParams_init_zero      {false, 0}
#define targetAutoTimerParams_init_zero          {false, 0, false, 0}
#define targetAutoLuxParams_init_zero            {false, 0, false, 0}
#define targetConfigurations_init_zero           {false, targetPowerStateParams_init_zero, false, targetControlPolicy_init_zero, false, targetAutoTimerParams_init_zero, false, targetAutoLuxParams_init_zero, false, targetManualControlParams_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define targetAutoLuxParams_targetOnLux_tag      1
#define targetAutoLuxParams_targetOffLux_tag     2
#define targetAutoTimerParams_targetOnTime_tag   1
#define targetAutoTimerParams_targetOffTime_tag  2
#define targetControlPolicy_controlPolicy_tag    1
#define targetManualControlParams_targetBrightnessLevel_tag 1
#define targetPowerStateParams_targetPowerState_tag 1
#define targetConfigurations_PowerState_tag      1
#define targetConfigurations_ControlPolicy_tag   2
#define targetConfigurations_AutoTimerParams_tag 3
#define targetConfigurations_AutoLuxParams_tag   4
#define targetConfigurations_ManualControlParams_tag 5

/* Struct field encoding specification for nanopb */
extern const pb_field_t targetPowerStateParams_fields[2];
extern const pb_field_t targetControlPolicy_fields[2];
extern const pb_field_t targetManualControlParams_fields[2];
extern const pb_field_t targetAutoTimerParams_fields[3];
extern const pb_field_t targetAutoLuxParams_fields[3];
extern const pb_field_t targetConfigurations_fields[6];

/* Maximum encoded size of messages (where known) */
#define targetPowerStateParams_size              2
#define targetControlPolicy_size                 2
#define targetManualControlParams_size           6
#define targetAutoTimerParams_size               12
#define targetAutoLuxParams_size                 12
#define targetConfigurations_size                44

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define ACTUATED_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
