/* Automatically generated nanopb header */
/* Generated by nanopb-0.3.9-dev at Mon Aug  7 14:29:50 2017. */

#ifndef PB_CONFIG_PB_H_INCLUDED
#define PB_CONFIG_PB_H_INCLUDED
#include <pb.h>

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _config_values {
    int32_t led_brightness;
/* @@protoc_insertion_point(struct:config_values) */
} config_values;

/* Default values for struct fields */

/* Initializer values for message structs */
#define config_values_init_default               {0}
#define config_values_init_zero                  {0}

/* Field tags (for use in manual encoding/decoding) */
#define config_values_led_brightness_tag         1

/* Struct field encoding specification for nanopb */
extern const pb_field_t config_values_fields[2];

/* Maximum encoded size of messages (where known) */
#define config_values_size                       11

/* Message IDs (where set with "msgid" option) */
#ifdef PB_MSGID

#define CONFIG_MESSAGES \


#endif

#ifdef __cplusplus
} /* extern "C" */
#endif
/* @@protoc_insertion_point(eof) */

#endif
