/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Tue Aug 22 16:34:11 2017. */

#include "actuated.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t targetPowerStateParams_fields[2] = {
    PB_FIELD(  1, BOOL    , REQUIRED, STATIC  , FIRST, targetPowerStateParams, targetPowerState, targetPowerState, 0),
    PB_LAST_FIELD
};

const pb_field_t targetControlPolicy_fields[2] = {
    PB_FIELD(  1, UENUM   , REQUIRED, STATIC  , FIRST, targetControlPolicy, controlPolicy, controlPolicy, 0),
    PB_LAST_FIELD
};

const pb_field_t targetManualControlParams_fields[2] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, targetManualControlParams, targetBrightnessLevel, targetBrightnessLevel, 0),
    PB_LAST_FIELD
};

const pb_field_t targetAutoTimerParams_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, targetAutoTimerParams, targetOnTime, targetOnTime, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, targetAutoTimerParams, targetOffTime, targetOnTime, 0),
    PB_LAST_FIELD
};

const pb_field_t targetAutoLuxParams_fields[3] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, targetAutoLuxParams, targetOnLux, targetOnLux, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, targetAutoLuxParams, targetOffLux, targetOnLux, 0),
    PB_LAST_FIELD
};

const pb_field_t targetConfigurations_fields[6] = {
    PB_FIELD(  1, MESSAGE , OPTIONAL, STATIC  , FIRST, targetConfigurations, PowerState, PowerState, &targetPowerStateParams_fields),
    PB_FIELD(  2, MESSAGE , OPTIONAL, STATIC  , OTHER, targetConfigurations, ControlPolicy, PowerState, &targetControlPolicy_fields),
    PB_FIELD(  3, MESSAGE , OPTIONAL, STATIC  , OTHER, targetConfigurations, AutoTimerParams, ControlPolicy, &targetAutoTimerParams_fields),
    PB_FIELD(  4, MESSAGE , OPTIONAL, STATIC  , OTHER, targetConfigurations, AutoLuxParams, AutoTimerParams, &targetAutoLuxParams_fields),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, targetConfigurations, ManualControlParams, AutoLuxParams, &targetManualControlParams_fields),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(targetConfigurations, PowerState) < 65536 && pb_membersize(targetConfigurations, ControlPolicy) < 65536 && pb_membersize(targetConfigurations, AutoTimerParams) < 65536 && pb_membersize(targetConfigurations, AutoLuxParams) < 65536 && pb_membersize(targetConfigurations, ManualControlParams) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_targetPowerStateParams_targetControlPolicy_targetManualControlParams_targetAutoTimerParams_targetAutoLuxParams_targetConfigurations)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(targetConfigurations, PowerState) < 256 && pb_membersize(targetConfigurations, ControlPolicy) < 256 && pb_membersize(targetConfigurations, AutoTimerParams) < 256 && pb_membersize(targetConfigurations, AutoLuxParams) < 256 && pb_membersize(targetConfigurations, ManualControlParams) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_targetPowerStateParams_targetControlPolicy_targetManualControlParams_targetAutoTimerParams_targetAutoLuxParams_targetConfigurations)
#endif


/* @@protoc_insertion_point(eof) */
