/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Mon Aug  7 14:29:50 2017. */

#include "config.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t config_values_fields[2] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, config_values, led_brightness, led_brightness, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
