/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Mon Aug  7 13:57:53 2017. */

#include "message.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t sensor_values_fields[6] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, sensor_values, ambient_lux, ambient_lux, 0),
    PB_FIELD(  2, INT32   , REQUIRED, STATIC  , OTHER, sensor_values, led_lux, ambient_lux, 0),
    PB_FIELD(  3, INT32   , REQUIRED, STATIC  , OTHER, sensor_values, power, led_lux, 0),
    PB_FIELD(  4, INT32   , REQUIRED, STATIC  , OTHER, sensor_values, temperature, power, 0),
    PB_FIELD(  5, INT32   , REQUIRED, STATIC  , OTHER, sensor_values, batteryLevel, temperature, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
