/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.9-dev at Mon Aug 21 15:40:50 2017. */

#include "sensed.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t sensor_values_fields[8] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, sensor_values, dataSamplingInstant, dataSamplingInstant, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, sensor_values, caseTemperature, dataSamplingInstant, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, sensor_values, powerConsumption, caseTemperature, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, sensor_values, luxOutput, powerConsumption, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, sensor_values, ambientLux, luxOutput, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, sensor_values, batteryLevel, ambientLux, 0),
    PB_FIELD(  7, BOOL    , OPTIONAL, STATIC  , OTHER, sensor_values, slaveAlive, batteryLevel, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
