# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='',
  serialized_pb=_b('\n\rmessage.proto\"o\n\rsensor_values\x12\x13\n\x0b\x61mbient_lux\x18\x01 \x02(\x05\x12\x0f\n\x07led_lux\x18\x02 \x02(\x05\x12\r\n\x05power\x18\x03 \x02(\x05\x12\x13\n\x0btemperature\x18\x04 \x02(\x05\x12\x14\n\x0c\x62\x61tteryLevel\x18\x05 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SENSOR_VALUES = _descriptor.Descriptor(
  name='sensor_values',
  full_name='sensor_values',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ambient_lux', full_name='sensor_values.ambient_lux', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='led_lux', full_name='sensor_values.led_lux', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='power', full_name='sensor_values.power', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='sensor_values.temperature', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batteryLevel', full_name='sensor_values.batteryLevel', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=128,
)

DESCRIPTOR.message_types_by_name['sensor_values'] = _SENSOR_VALUES

sensor_values = _reflection.GeneratedProtocolMessageType('sensor_values', (_message.Message,), dict(
  DESCRIPTOR = _SENSOR_VALUES,
  __module__ = 'message_pb2'
  # @@protoc_insertion_point(class_scope:sensor_values)
  ))
_sym_db.RegisterMessage(sensor_values)


# @@protoc_insertion_point(module_scope)
